name: GeneratePlantumlImages

on:
  workflow_dispatch:

  push:
    branches: 
    - '*'
    paths: 
    - 'src/plantuml/**'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Java distribution for running the plantUML jar
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
      
      # Install graphviz for plantuml     
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      
      # Download plantUML jar 
      - name: Download plantuml file
        run: |
          wget -O plantuml.jar "https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar" 

      # Runs a single command using the runners shell
      - name: Generate images
        run: |
          imagedir=images/diagrams
          mkdir -p $imagedir
          rm -rf images/diagrams/*
          for fullname in $(find src/plantuml/ -type f -name '*.puml')
          do
              echo "Fullname: ${fullname}"
              base=$(basename "${fullname}" .puml)
              dir=$(dirname $fullname)
              echo "Basename: ${base}"
              outdir=$(dirname $fullname | sed s+src/plantuml+${imagedir}+)
              echo "Outdir: ${outdir}"
              mkdir -p $outdir
              
              
              # local method
              # cp $fullname tmp.puml  # because of filename bug in plantuml.jar (dots in filename are not suppoerted)
              # tmpname=$dir/tmp.puml
              # java -jar plantuml.jar -tpng -checkmetadata -o $outdir $tmpname
              # mv ${outdir}/${tmpname} ${outdir}/${base}.png
              # java -jar plantuml.jar -tsvg -checkmetadata -o $outdir $tmpname
              # mv ${outdir}/${tmpname} ${outdir}/${base}.svg
              # rm -f $dir/tmp.puml
              
              # method with pipes
              cat "${fullname}" | java -jar plantuml.jar -p -tpng -checkmetadata  > "${outdir}/${base}.png"
              cat "${fullname}" | java -jar plantuml.jar -p -tsvg -checkmetadata  > "${outdir}/${base}.svg"
          done
          tree ./
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8
        with:
          add: 'images/diagrams/'
